spring.config.import=optional:file:.env
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gordoarepas_dev}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:MiPassword123}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
#server.port=${PORT:8080}

server.address=0.0.0.0
server.port=8080

# CORS: coma-separado
app.cors.allowed-origins=${APP_CORS_ORIGINS:http://localhost:5173,https://garepas-app.vercel.app}
